=== nhl/link-move/link-move/src/main/resources/com/nhl/link/move/xsd/extractor_config_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://linkmove.io/xsd/extractor_config_2.xsd"
	xmlns:tns="http://linkmove.io/xsd/extractor_config_2.xsd" elementFormDefault="qualified">

	<annotation>
		<documentation xml:lang="en">
			LinkMove Extractor config schema. Provides a structured way to configure an
			arbitrary extractor.
		</documentation>
	</annotation>

	<element name="config" type="tns:ConfigType" />

	<complexType name="ConfigType">

		<annotation>
			<documentation source="description">
				Top-level element corresponding to ExtractorModelContainer object.
			</documentation>
		</annotation>

		<sequence>

			<element name="type" type="string" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation source="description">
						Defines "type" of the Extractor, such as "jdbc", "csv", "xml", etc.
						ExtractorModelContainer's type is inherited (and can be overridden) by extractors.
					</documentation>
				</annotation>
			</element>

			<choice minOccurs="1" maxOccurs="1">
				<element name="connectorId" type="tns:ConnectorIdType"/>
				<element name="connectorIds" type="tns:ConnectorIdsType"/>
			</choice>

			<element name="extractor" type="tns:ExtractorType" minOccurs="0" maxOccurs="unbounded" />

		</sequence>
	</complexType>

	<complexType name="ExtractorType">
		<sequence>

			<element name="name" type="string" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation source="description">
						Specifies the name unique within the container. If missing, the default name of
						"default_extractor" is used.
					</documentation>
				</annotation>
			</element>

			<element name="type" type="string" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation source="description">
						Overrides "type" of the container
					</documentation>
				</annotation>
			</element>

			<choice minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation source="description">
						Overrides "connectorId"/"connectorIds" of the container
					</documentation>
				</annotation>
				<element name="connectorId" type="tns:ConnectorIdType"/>
				<element name="connectorIds" type="tns:ConnectorIdsType"/>
			</choice>

			<element name="attributes" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation source="description">
						An optional list of attributes that maps source row keys to the target names.
					</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="attribute" type="tns:AttributeType" minOccurs="0" maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>

			<element name="properties" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation source="description">
						An list of Extractor-specific properties.
					</documentation>
				</annotation>

				<complexType>
					<sequence>
						<any processContents="skip" minOccurs="0" maxOccurs="unbounded">
							<annotation>
								<documentation source="description">
									Each property tag name becomes a property name. Often Extractors are using
									naming conventions, structuring property names like this: "extractor.jdbc.sqltemplate".
									Here the first part is a
									fixed prefix ("extractor"), second is Extractor type ("jdbc"),
									third - property name understood by the given
									Extractor.
								</documentation>
							</annotation>
						</any>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="AttributeType">
		<sequence>
			<element name="type" type="string" minOccurs="1" maxOccurs="1" />
			<element name="source" type="string" minOccurs="0" maxOccurs="1" />
			<element name="target" type="string" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="ConnectorIdsType">
		<sequence>
			<element name="connectorId" type="tns:ConnectorIdType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

	<simpleType name="ConnectorIdType">
		<annotation>
			<documentation source="description">
				Defines a symbolic ID of the connector used by the extractor. Connector must
				be
				compatible with Extractor type specified above. ExtractorModelContainer's connectorId is inherited (and can be
				overridden) by extractors.
			</documentation>
		</annotation>
		<restriction base="string"/>
	</simpleType>

</schema>

=== nhl/link-move/src/test/resources/com/nhl/link/etl/itest/etl1_to_etl1t_lower.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nhl.github.io/link-etl/xsd/extractor_config_2.xsd"
	xmlns="http://nhl.github.io/link-etl/xsd/extractor_config_2.xsd">
	<type>jdbc</type>
	<connectorId>derbysrc</connectorId>
	<extractor>
		<attributes>
			<attribute>
				<type>java.lang.Integer</type>
				<source>age</source>
				<target>age</target>
			</attribute>
			<attribute>
				<type>java.lang.String</type>
				<source>description</source>
				<target>description</target>
			</attribute>
			<attribute>
				<type>java.lang.String</type>
				<source>name</source>
				<target>name</target>
			</attribute>
		</attributes>
		<properties>
			<extractor.jdbc.sqltemplate>
			<![CDATA[SELECT age, description, name FROM utest.etl1
			]]>
			</extractor.jdbc.sqltemplate>
			<extractor.jdbc.sqltemplate.caps>lower
			</extractor.jdbc.sqltemplate.caps>
		</properties>
	</extractor>
</config>

=== nhl/link-move/link-move/src/test/resources/com/nhl/link/move/itest/etl3_to_etl3t_normalizers.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://linkmove.io/xsd/extractor_config_2.xsd"
	xmlns="http://linkmove.io/xsd/extractor_config_2.xsd">
	<type>jdbc</type>
	<connectorId>derbysrc</connectorId>
	<extractor>
		<attributes>
			<attribute>
				<type>java.lang.String</type>
				<source>e2_id</source>
				<target>e2</target>
			</attribute>
			<attribute>
				<type>java.lang.String</type>
				<source>name</source>
				<target>name</target>
			</attribute>
		</attributes>
		<properties>
			<extractor.jdbc.sqltemplate>
			<![CDATA[SELECT CAST(e2_id AS CHAR) e2_id, name FROM utest.etl3
			]]>
			</extractor.jdbc.sqltemplate>
			<extractor.jdbc.sqltemplate.caps>lower
			</extractor.jdbc.sqltemplate.caps>
		</properties>
	</extractor>
</config>

=== nhl/link-move/link-move/src/test/resources/com/nhl/link/move/itest/etl1_to_etl1t.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://linkmove.io/xsd/extractor_config_2.xsd"
	xmlns="http://linkmove.io/xsd/extractor_config_2.xsd">
	<type>jdbc</type>
	<connectorId>derbysrc</connectorId>
	<extractor>
		<attributes>
			<attribute>
				<type>java.lang.Integer</type>
				<source>AGE</source>
				<target>age</target>
			</attribute>
			<attribute>
				<type>java.lang.String</type>
				<source>DESCRIPTION</source>
				<target>description</target>
			</attribute>
			<attribute>
				<type>java.lang.String</type>
				<source>NAME</source>
				<target>name</target>
			</attribute>
		</attributes>
		<properties>
			<extractor.jdbc.sqltemplate>
			<![CDATA[SELECT age, description, name FROM utest.etl1
			]]>
			</extractor.jdbc.sqltemplate>
		</properties>
	</extractor>
</config>

=== nhl/link-move/link-move/src/test/resources/com/nhl/link/move/itest/etl1_to_etl1t_multiconnectors.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://linkmove.io/xsd/extractor_config_2.xsd"
	xmlns="http://linkmove.io/xsd/extractor_config_2.xsd">
	<type>xml</type>
	<connectorIds>
		<connectorId>/com/nhl/link/move/itest/xml/etl1_1.xml</connectorId>
		<connectorId>/com/nhl/link/move/itest/xml/etl1_2.xml</connectorId>
	</connectorIds>
	<extractor>
		<attributes>
			<attribute>
				<type>java.lang.Integer</type>
				<source>age</source>
				<target>age</target>
			</attribute>
			<attribute>
				<type>java.lang.String</type>
				<source>name</source>
				<target>name</target>
			</attribute>
		</attributes>
		<properties>
			<extractor.xml.xpathexpression>/docroot/element</extractor.xml.xpathexpression>
		</properties>
	</extractor>
</config>

=== nhl/link-move/link-move/src/test/resources/com/nhl/link/move/itest/etl4_to_etl4t_converters.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://linkmove.io/xsd/extractor_config_2.xsd"
	xmlns="http://linkmove.io/xsd/extractor_config_2.xsd">
	<type>jdbc</type>
	<connectorId>derbysrc</connectorId>
	<extractor>
		<attributes>
			<attribute>
				<type>java.lang.Integer</type>
				<source>id</source>
				<target>db:id</target>
			</attribute>
			<attribute>
				<type>java.lang.Integer</type>
				<source>c_boolean</source>
				<target>db:c_boolean</target>
			</attribute>
			<attribute>
				<type>java.lang.Integer</type>
				<source>c_enum</source>
				<target>db:c_enum</target>
			</attribute>
		</attributes>
		<properties>
			<extractor.jdbc.sqltemplate>
			<![CDATA[SELECT id,
			 	#result('c_boolean', 'java.lang.Integer'),
			 	#result('c_enum', 'java.lang.String')
				FROM utest.etl4
			]]>
			</extractor.jdbc.sqltemplate>
			<extractor.jdbc.sqltemplate.caps>lower
			</extractor.jdbc.sqltemplate.caps>
		</properties>
	</extractor>
</config>

=== nhl/link-move/link-move/src/test/resources/com/nhl/link/move/itest/etl1_to_etl1t_extra_source_columns.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://linkmove.io/xsd/extractor_config_2.xsd"
	xmlns="http://linkmove.io/xsd/extractor_config_2.xsd">
	<type>jdbc</type>
	<connectorId>derbysrc</connectorId>
	<extractor>
		<attributes>
			<attribute>
				<type>java.lang.String</type>
				<source>NAME</source>
				<target>name</target>
			</attribute>
			<attribute>
				<type>java.lang.String</type>
				<source>DL</source>
				<!-- TODO: invalid target property is NOT OK... 
				     we are ignoring it per #59, but we should actually throw.
				     Pending https://github.com/nhl/link-move/issues/63
				      -->
				<target>noSuchProperty</target>
			</attribute>
		</attributes>
		<properties>
			<extractor.jdbc.sqltemplate>
			<![CDATA[SELECT name, LENGTH(description) as DL FROM utest.etl1
			]]>
			</extractor.jdbc.sqltemplate>
		</properties>
	</extractor>
</config>

=== nhl/link-move/src/test/resources/com/nhl/link/etl/extractor/parser/extractor_v2.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nhl.github.io/link-etl/xsd/extractor_config_2.xsd"
	xmlns="http://nhl.github.io/link-etl/xsd/extractor_config_2.xsd">

	<type>atype</type>
	<connectorId>aconnector</connectorId>

	<extractor>

		<name>e1</name>
		<attributes>
			<attribute>
				<type>java.lang.String</type>
				<source>a1</source>
				<target>a_1</target>
			</attribute>
			<attribute>
				<type>java.lang.Integer</type>
				<source>a2</source>
				<target>a_2</target>
			</attribute>
			<attribute>
				<type>java.lang.Integer</type>
				<source>a2</source>
			</attribute>
		</attributes>

		<properties>
			<a.b>AB1</a.b>
			<x.y>XY1</x.y>
		</properties>
	</extractor>

	<extractor>

		<name>e2</name>
		<type>atype2</type>
		<connectorId>aconnector2</connectorId>

		<properties>
			<a.b>AB2</a.b>
			<x.y>XY2</x.y>
		</properties>
	</extractor>

	<extractor>
		<!-- default name -->
	</extractor>

</config>
