=== nhl/link-move/xsd/extractor_config_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://nhl.github.io/link-etl/schema/extractor_config/extractor_config_1.xsd"
	xmlns:tns="http://nhl.github.io/link-etl/schema/extractor_config/extractor_config_1.xsd" elementFormDefault="qualified">

	<annotation>
		<documentation xml:lang="en">
			LinkETL Extractor config schema. Provides a structured way to configure an
			arbitrary ETL extractor.
		</documentation>
	</annotation>

	<element name="config" type="tns:ConfigType" />


	<complexType name="ConfigType">
		<annotation>
			<documentation source="description">
				Top level element
			</documentation>
		</annotation>
		<sequence>

			<element name="type" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation source="description">
						Defines "type" of the Extractor, such as "jdbc", "csv", "xml", etc.
					</documentation>
				</annotation>
			</element>

			<element name="connectorId" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation source="description">
						Defines a symbolic ID of the connector used by the extractor. Connector must
						be
						compatible with Extrator type specified above.
					</documentation>
				</annotation>
			</element>

			<element name="attributes" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation source="description">
						An optional list of attributes that maps source row keys to the target names.
					</documentation>
				</annotation>
				<complexType>
					<sequence>
						<element name="attribute" type="tns:AttributeType" minOccurs="0" maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>


			<element name="properties" minOccurs="0" maxOccurs="1">
				<annotation>
					<documentation source="description">
						An list of Extractor-specific properties used to configure an arbitrary
						extractor.
					</documentation>
				</annotation>

				<complexType>
					<sequence>
						<any processContents="skip" minOccurs="0" maxOccurs="unbounded">
							<annotation>
								<documentation source="description">
									Each property tag name becomes a property name. Often Extractors are using
									naming conventions, structuring property names like this: "extractor.jdbc.sqltemplate".
									Here the first part is a
									fixed prefix ("extractor"), second is Extractor type ("jdbc"),
									third - property name understood by the given
									Extractor.
								</documentation>
							</annotation>
						</any>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>



	<complexType name="AttributeType">
		<sequence>
			<element name="type" type="string" minOccurs="1" maxOccurs="1" />
			<element name="source" type="string" minOccurs="0" maxOccurs="1" />
			<element name="target" type="string" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>


</schema>

=== nhl/link-move/src/test/resources/com/nhl/link/etl/itest/etl3_to_etl3t.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nhl.github.io/link-etl/schema/extractor_config/extractor_config_1.xsd"
	xmlns="http://nhl.github.io/link-etl/schema/extractor_config">
	<type>jdbc</type>
	<connectorId>derbysrc</connectorId>
	<attributes>
		<attribute>
			<type>java.lang.Integer</type>
			<source>e2_id</source>
			<target>e2</target>
		</attribute>
		<attribute>
			<type>java.lang.Integer</type>
			<source>e5_id</source>
			<target>e5</target>
		</attribute>
		<attribute>
			<type>java.lang.String</type>
			<source>name</source>
			<target>name</target>
		</attribute>
		<attribute>
			<type>java.lang.String</type>
			<source>phone_number</source>
			<target>phoneNumber</target>
		</attribute>
	</attributes>
	<properties>
		<extractor.jdbc.sqltemplate>
			<![CDATA[SELECT e2_id, e5_id, name, phone_number FROM utest.etl3
			]]>
		</extractor.jdbc.sqltemplate>
		<extractor.jdbc.sqltemplate.caps>lower
		</extractor.jdbc.sqltemplate.caps>
	</properties>
</config>
